---
kind: pipeline
name: default

clone:
  disable: true

workspace:
  base: /workspace
  path: src/github.com/bitpoke/wordpress-operator

steps:
- name: git
  pull: default
  image: plugins/git
  settings:
    depth: 0
    tags: true

- name: install dependencies
  pull: always
  image: docker.io/bitpoke/build:v0.3.0-3.g7069e76
  commands:
  - make -j4 build.tools

- name: verify generated code
  image: docker.io/bitpoke/build:v0.3.0-3.g7069e76
  commands:
  - make generate
  - git diff --exit-code

- name: lint
  image: docker.io/bitpoke/build:v0.3.0-3.g7069e76
  commands:
  - make -j4 lint

- name: test
  image: docker.io/bitpoke/build:v0.3.0-3.g7069e76
  commands:
  - make test

- name: build
  image: docker.io/bitpoke/build:v0.3.0-3.g7069e76
  commands:
  - make -j4 build

- name: publish
  image: docker.io/bitpoke/build:v0.3.0-3.g7069e76
  environment:
    DOCKER_REGISTRY:
      from_secret: DOCKER_REGISTRY
    DOCKER_USERNAME:
      from_secret: DOCKER_USERNAME
    DOCKER_PASSWORD:
      from_secret: DOCKER_PASSWORD
  commands:
  - /usr/local/bin/setup-credentials-helper.sh
  - make publish
  when:
    event:
      - push
      - tag

services:
- name: docker
  image: docker:dind
  privileged: true
  commands:
    - /usr/local/bin/dockerd-entrypoint.sh dockerd --host "unix:///workspace/docker.sock" --storage-driver overlay2 --log-level error

trigger:
  ref:
    - refs/pull/**
    - refs/heads/master
    - refs/heads/release-*
    - refs/tags/**
