{{- if .Values.rbac.create }}
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "wordpress-operator.fullname" . }}
  labels:
    {{- include "wordpress-operator.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ template "wordpress-operator.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ template "wordpress-operator.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
