apiVersion: v1
kind: Service
metadata:
  name: {{ include "wordpress-operator.fullname" . }}
  labels:
    {{- include "wordpress-operator.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 9125
      targetPort: prometheus
      protocol: TCP
      name: prometheus
  selector:
    {{- include "wordpress-operator.selectorLabels" . | nindent 4 }}
